apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'alertmanager@devops-lab.com'
              smtp_auth_username: 'kingwinlimo@gmail.com'
              smtp_auth_password: 'bwjxlgizsoaqeevc'
              smtp_require_tls: true
            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 1h
              receiver: 'email-receiver'
              routes:
              - receiver: 'null'
                matchers:
                - alertname = "Watchdog"
            receivers:
            - name: 'null'
            - name: 'email-receiver'
              email_configs:
              - to: 'kingwinlimo@gmail.com'
                send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true