apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nghia1245654/lab_gitops.git
    path: todo
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
